# Generated by Django 4.2.10 on 2024-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='units_wt',
        ),
        migrations.AlterField(
            model_name='time',
            name='I',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Сила тока'),
        ),
        migrations.AlterField(
            model_name='time',
            name='S',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Площадь покрытия'),
        ),
        migrations.AlterField(
            model_name='time',
            name='h',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Толщина покрытия'),
        ),
        migrations.AlterField(
            model_name='time',
            name='j',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Плотность тока'),
        ),
        migrations.AlterField(
            model_name='time',
            name='m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Масса покрытия'),
        ),
        migrations.AlterField(
            model_name='time',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Плотность покрытия'),
        ),
        migrations.AlterField(
            model_name='time',
            name='q',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Электрохимический эквивалент'),
        ),
        migrations.AlterField(
            model_name='time',
            name='t',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='time',
            name='wt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Выход по току'),
        ),
    ]
