# Generated by Django 4.2.10 on 2024-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electrochemicalequivalents',
            options={'ordering': ('name', 'q'), 'verbose_name': 'Материал покрытия', 'verbose_name_plural': 'Материалы покрытия'},
        ),
        migrations.AlterField(
            model_name='electrochemicalequivalents',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Плотность покрытия (кг/м3)'),
        ),
        migrations.AlterField(
            model_name='electrochemicalequivalents',
            name='q',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Электрохимический эквивалент (мг/кулон)'),
        ),
    ]
