# Generated by Django 4.2.10 on 2024-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_electrochemicalequivalents_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amperage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Площадь покрытия')),
                ('units_S', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы площади')),
                ('j', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Плотность тока')),
                ('units_j', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы плотности тока')),
                ('I', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Сила тока')),
                ('units_I', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы силы тока')),
            ],
            options={
                'verbose_name': 'Расчет силы тока',
                'verbose_name_plural': 'Расчеты сил тока',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CurrentDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Площадь покрытия')),
                ('units_S', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы площади')),
                ('j', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Плотность тока')),
                ('units_j', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы плотности тока')),
                ('I', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Сила тока')),
                ('units_I', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы силы тока')),
            ],
            options={
                'verbose_name': 'Расчет плотности тока',
                'verbose_name_plural': 'Расчеты плотностей тока',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Скорость осаждения')),
                ('units_v', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы скорости осаждения')),
                ('t', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Время покрытия')),
                ('units_t', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы времени покрытия')),
                ('p', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Плотность покрытия')),
                ('units_p', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы плотности покрытия')),
                ('q', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Электрохимический эквивалент')),
                ('units_q', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы электрохимического эквивалента')),
                ('wt', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Выход по току')),
                ('I', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Сила тока')),
                ('units_I', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы силы тока')),
                ('S', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Площадь покрытия')),
                ('units_S', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы площади')),
                ('m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Масса покрытия')),
                ('units_m', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы массы покрытия')),
                ('h', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Толщина покрытия')),
            ],
            options={
                'verbose_name': 'Расчет толщины покрытия',
                'verbose_name_plural': 'Расчеты толщин покрытия',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Сила тока')),
                ('units_I', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы силы тока')),
                ('t', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Время покрытия')),
                ('units_t', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы времени покрытия')),
                ('q', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Электрохимический эквивалент')),
                ('units_q', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы электрохимического эквивалента')),
                ('wt', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Выход по току')),
                ('j', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Плотность тока')),
                ('units_j', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы плотности тока')),
                ('S', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Площадь покрытия')),
                ('units_S', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы площади')),
                ('p', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Плотность покрытия')),
                ('units_p', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы плотности покрытия')),
                ('h', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Толщина покрытия')),
                ('units_h', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы толщины покрытия')),
                ('m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Масса покрытия')),
            ],
            options={
                'verbose_name': 'Расчет массы покрытия',
                'verbose_name_plural': 'Расчеты масс покрытия',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ('id',), 'verbose_name': 'Расчет времени', 'verbose_name_plural': 'Расчеты времени'},
        ),
    ]
