# Generated by Django 4.2.10 on 2024-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_amperage_currentdensity_height_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='height',
            name='j',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Плотность тока'),
        ),
        migrations.AddField(
            model_name='height',
            name='units_j',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы плотности тока'),
        ),
    ]
