# Generated by Django 4.2.10 on 2024-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_electrochemicalequivalents_p_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='height',
            options={'ordering': ('-id',), 'verbose_name': 'Расчет толщины покрытия', 'verbose_name_plural': 'Расчеты толщин покрытия'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ('-id',), 'verbose_name': 'Расчет времени', 'verbose_name_plural': 'Расчеты времени'},
        ),
        migrations.AlterField(
            model_name='height',
            name='I',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Сила тока'),
        ),
        migrations.AlterField(
            model_name='height',
            name='S',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Площадь покрытия'),
        ),
        migrations.AlterField(
            model_name='height',
            name='h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Толщина покрытия (в метрах)'),
        ),
        migrations.AlterField(
            model_name='height',
            name='j',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Плотность тока'),
        ),
        migrations.AlterField(
            model_name='height',
            name='m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Масса покрытия'),
        ),
        migrations.AlterField(
            model_name='height',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Плотность покрытия'),
        ),
        migrations.AlterField(
            model_name='height',
            name='q',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Электрохимический эквивалент'),
        ),
        migrations.AlterField(
            model_name='height',
            name='t',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Время покрытия'),
        ),
        migrations.AlterField(
            model_name='height',
            name='v',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Скорость осаждения'),
        ),
        migrations.AlterField(
            model_name='height',
            name='wt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Выход по току'),
        ),
    ]
