# Generated by Django 4.2.10 on 2024-05-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_weight_i_alter_weight_s_alter_weight_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='height',
            name='h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Толщина покрытия (в мкм)'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Масса покрытия (в мг)'),
        ),
    ]
